name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - 'v*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: 1.20.x
            otp: 29
          - elixir: 1.19.x
            otp: 28
          - elixir: 1.18.x
            otp: 27

    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0

    - name: Set up Elixir
      id: beam
      uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore dependencies cache
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      with:
        path: deps
        key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Setup EventStore test databases
      run: |
        MIX_ENV=test mix event_store.setup
        MIX_ENV=jsonb mix event_store.setup
        MIX_ENV=text_ids mix event_store.setup

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Run tests
      run: mix test.all

    - name: Retrieve Dialyzer PLT cache
      uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c # v3.5.0
      id: plt-cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-plts-${{ hashFiles('**/mix.lock') }}

    - name: Create Dialyzer PLTs
      if: steps.plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt

    - name: Run Dialyzer
      run: mix dialyzer --no-check
